In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

np.random.seed(42)

### Categories and subcategories

In [2]:
categories = {
    "Food & Beverages": [
        "Beverages",
        "Snacks",
        "Dairy",
        "Grocery",
        "Bakery"
    ],
    
    "Personal Care": [
        "Hair Care",
        "Oral Care",
        "Body Care",
        "Shaving"
    ],
    
    "Household": [
        "Cleaning",
        "Laundry",
        "Kitchen",
        "Paper Products"
    ],
    
    "Beauty": [
        "Skincare",
        "Makeup",
        "Fragrance",
        "Hair Styling"
    ],
    
    "Health & Wellness": [
        "Vitamins",
        "Fitness",
        "Personal Health",
        "Wellness"
    ],
    
    "Baby Care": [
        "Diapers",
        "Baby Food",
        "Baby Bath",
        "Baby Accessories"
    ],
    
    "Electronics": [
        "Mobile Accessories",
        "Small Electronics",
        "Cables & Chargers",
        "Home Electronics"
    ],
    
    "Fresh Food": [
        "Fruits",
        "Vegetables",
        "Meat",
        "Bakery Fresh"
    ]
}

### Brands

In [3]:
brands = [
    "Gulf Fresh",
    "Desert Harvest",
    "Nakhla",
    "Oasis Choice",
    "Arabian Select",
    "Golden Basket",
    "Sahara Home",
    "Rimal",
    "Palm Valley",
    "Al Waha",
    "Eastern Choice",
    "Northern Star"
]

### Create Product IDs

In [4]:
product_ids = [
    f"P{i:04d}"
    for i in range(1, 501)
]

In [5]:
product_ids[:10]

['P0001',
 'P0002',
 'P0003',
 'P0004',
 'P0005',
 'P0006',
 'P0007',
 'P0008',
 'P0009',
 'P0010']

### Generate Category/Subcategory

In [6]:
category_weights = {
    "Food & Beverages": 0.22,
    "Personal Care": 0.12,
    "Household": 0.13,
    "Beauty": 0.10,
    "Health & Wellness": 0.10,
    "Baby Care": 0.08,
    "Electronics": 0.10,
    "Fresh Food": 0.15
}

In [7]:
category_list = list(category_weights.keys())
category_probabilities = list(category_weights.values())

### Generate categories

In [8]:
product_categories = np.random.choice(
    category_list,
    size=500,
    p=category_probabilities
)

### Generate subcategory

In [9]:
product_categories = np.random.choice(
    category_list,
    size=500,
    p=category_probabilities
)

### Generate Brands

In [10]:
product_brands = np.random.choice(
    brands,
    size=500
)

### Category Product Names

In [12]:
product_name = [
    f"{brand} {subcategory} Item {i:03d}"
    for i, (brand, subcategory) 
    in enumerate(
        zip(product_brands, product_categories),
        start=1
    )
]

### Generate Product Costs

In [13]:
cost_ranges = {
    "Food & Beverages": (2, 80),
    "Personal Care": (5, 120),
    "Household": (5, 150),
    "Beauty": (10, 250),
    "Health & Wellness": (10, 200),
    "Baby Care": (8, 180),
    "Electronics": (20, 800),
    "Fresh Food": (3, 100)
}

In [14]:
unit_costs = [
    round(
        np.random.uniform(
            cost_ranges[category][0],
            cost_ranges[category][1]
        ),
        2
    )
    for category in product_categories
]

### Generate Selling Prices

In [15]:
markup_ranges = {
    "Food & Beverages": (0.15, 0.35),
    "Personal Care": (0.25, 0.50),
    "Household": (0.20, 0.40),
    "Beauty": (0.35, 0.70),
    "Health & Wellness": (0.30, 0.60),
    "Baby Care": (0.20, 0.45),
    "Electronics": (0.10, 0.30),
    "Fresh Food": (0.20, 0.40)
}

In [16]:
selling_prices = [
    round(
        cost * (
            1 + np.random.uniform(
                markup_ranges[category][0],
                markup_ranges[category][1]
            )
        ),
        2
    )
    for cost, category in zip(
        unit_costs,
        product_categories
    )
]

### Create the DataFrame

In [18]:
df_product = pd.DataFrame({
    "product_id": product_ids,
    "product_name": product_name,
    "category": product_categories,
    "subcategory": product_categories,
    "brand": product_brands,
    "unit_cost": unit_costs,
    "selling_price": selling_prices
})

In [19]:
df_product.head(10)

,product_id,product_name,category,subcategory,brand,unit_cost,selling_price
0,P0001,Northern Star Baby Care Item 001,Baby Care,Baby Care,Northern Star,81.18,102.30
1,P0002,Rimal Beauty Item 002,Beauty,Beauty,Rimal,93.02,129.53
2,P0003,Nakhla Personal Care Item 003,Personal Care,Personal Care,Nakhla,47.67,61.94
3,P0004,Rimal Electronics Item 004,Electronics,Electronics,Rimal,790.37,1009.61
4,P0005,Arabian Select Baby Care Item 005,Baby Care,Baby Care,Arabian Select,14.90,20.29
5,P0006,Gulf Fresh Food & Beverages Item 006,Food & Beverages,Food & Beverages,Gulf Fresh,69.63,84.06
6,P0007,Sahara Home Fresh Food Item 007,Fresh Food,Fresh Food,Sahara Home,59.13,80.61
7,P0008,Arabian Select Electronics Item 008,Electronics,Electronics,Arabian Select,362.12,460.72
8,P0009,Golden Basket Fresh Food Item 009,Fresh Food,Fresh Food,Golden Basket,73.35,100.44
9,P0010,Golden Basket Baby Care Item 010,Baby Care,Baby Care,Golden Basket,91.71,131.12

## Validation
### Shape

In [20]:
df_product.shape

(500, 7)

### Product ID uniqueness

In [21]:
df_product["product_id"].nunique()

500

### Category Distribution

In [22]:
df_product["category"].value_counts()

category
Food & Beverages     122
Household             71
Fresh Food            70
Personal Care         56
Health & Wellness     56
Beauty                49
Electronics           42
Baby Care             34
Name: count, dtype: int64

### Subcategory Validation

In [23]:
df_product.groupby(
    "category"
)["subcategory"].nunique()

category
Baby Care            1
Beauty               1
Electronics          1
Food & Beverages     1
Fresh Food           1
Health & Wellness    1
Household            1
Personal Care        1
Name: subcategory, dtype: int64

### Check Prices

In [24]:
df_product[
    ["unit_cost", "selling_price"]
].describe()

        unit_cost  selling_price
count  500.000000     500.000000
mean    99.034200     130.277100
std    117.282069     144.738415
min      2.590000       3.190000
25%     36.277500      47.642500
50%     66.585000      86.510000
75%    120.962500     163.702500
max    795.430000    1009.610000

In [25]:
(df_product["selling_price"] <= df_product["unit_cost"]).sum()

np.int64(0)

### Calculate Product Margin

In [26]:
df_product["expected_margin_pct"] = (
    (df_product["selling_price"] - df_product["unit_cost"])
    / df_product["selling_price"]
)

In [27]:
df_product["expected_margin_pct"].describe()

count    500.000000
mean       0.241692
std        0.061041
min        0.096713
25%        0.201099
50%        0.239409
75%        0.275209
max        0.410902
Name: expected_margin_pct, dtype: float64

### Check Category Margins

In [28]:
df_product.groupby("category")[
    "expected_margin_pct"
].mean().sort_values(ascending=False)

category
Beauty               0.343816
Health & Wellness    0.290574
Personal Care        0.273215
Baby Care            0.247217
Fresh Food           0.232067
Household            0.228428
Food & Beverages     0.200625
Electronics          0.168620
Name: expected_margin_pct, dtype: float64

In [29]:
df_product = df_product.drop(
    columns="expected_margin_pct"
)

In [30]:
df_product.columns

Index(['product_id', 'product_name', 'category', 'subcategory', 'brand',
       'unit_cost', 'selling_price'],
      dtype='str')

### Data Quality Check

In [31]:
df_product.isna().sum()

product_id       0
product_name     0
category         0
subcategory      0
brand            0
unit_cost        0
selling_price    0
dtype: int64

In [32]:
df_product.dtypes

product_id           str
product_name         str
category             str
subcategory          str
brand                str
unit_cost        float64
selling_price    float64
dtype: object

### Save to data/raw

In [33]:
df_product.to_csv(
    "../data/raw/dim_product.csv",
    index=False
)

In [34]:
Path(
    "../data/raw/dim_product.csv"
).exists()

True