In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
start_date = "2024-01-01"
end_date = "2025-12-31"

### Generate Every Date

In [3]:
dates = pd.date_range(
    start=start_date,
    end=end_date,
    freq="D"
)

In [4]:
len(dates)

731

### Create the DataFrame

In [5]:
df_date = pd.DataFrame({
    "date": dates
})

In [6]:
df_date.head()

        date
0 2024-01-01
1 2024-01-02
2 2024-01-03
3 2024-01-04
4 2024-01-05

### Add Year

In [7]:
df_date["year"] = df_date["date"].dt.year

### Add Quarter

In [8]:
df_date["quarter"] = (
    "Q" + df_date["date"].dt.quarter.astype(str)
)

### Add Month Number

In [9]:
df_date["month"] = df_date["date"].dt.month

### Add Month Name

In [10]:
df_date["month_name"] = (
    df_date["date"].dt.month_name()
)

### Add Week Number

In [11]:
df_date["week"] = (
    df_date["date"].dt.isocalendar().week.astype(int)
)

### Add Day of Week

In [12]:
df_date["day_of_week"] = (
    df_date["date"].dt.day_name()
)

### Add Day Number

In [13]:
df_date["day"] = df_date["date"].dt.day

### Add Weekend Flag

In [14]:
df_date["is_weekend"] = (
    df_date["date"].dt.dayofweek >= 4
)

In [15]:
df_date["is_weekend"].value_counts()

is_weekend
False    419
True     312
Name: count, dtype: int64

### Add Month-Year

In [16]:
df_date["month_year"] = (
    df_date["date"].dt.strftime("%Y-%m")
)

### Add Year-Month Sort Key

In [17]:
df_date["year_month"] = (
    df_date["year"] * 100
    + df_date["month"]
)

### Add Quarter Number

In [18]:
df_date["quarter_number"] = (
    df_date["date"].dt.quarter
)

In [19]:
df_date.head(10)

,date,year,quarter,month,month_name,week,day_of_week,day,is_weekend,month_year,year_month,quarter_number
0,2024-01-01,2024,Q1,1,January,1,Monday,1,False,2024-01,202401,1
1,2024-01-02,2024,Q1,1,January,1,Tuesday,2,False,2024-01,202401,1
2,2024-01-03,2024,Q1,1,January,1,Wednesday,3,False,2024-01,202401,1
3,2024-01-04,2024,Q1,1,January,1,Thursday,4,False,2024-01,202401,1
4,2024-01-05,2024,Q1,1,January,1,Friday,5,True,2024-01,202401,1
5,2024-01-06,2024,Q1,1,January,1,Saturday,6,True,2024-01,202401,1
6,2024-01-07,2024,Q1,1,January,1,Sunday,7,True,2024-01,202401,1
7,2024-01-08,2024,Q1,1,January,2,Monday,8,False,2024-01,202401,1
8,2024-01-09,2024,Q1,1,January,2,Tuesday,9,False,2024-01,202401,1
9,2024-01-10,2024,Q1,1,January,2,Wednesday,10,False,2024-01,202401,1

In [20]:
df_date.columns

Index(['date', 'year', 'quarter', 'month', 'month_name', 'week', 'day_of_week',
       'day', 'is_weekend', 'month_year', 'year_month', 'quarter_number'],
      dtype='str')

### Validate the Date Range

In [21]:
df_date["date"].min()

Timestamp('2024-01-01 00:00:00')

In [22]:
df_date["date"].max()

Timestamp('2025-12-31 00:00:00')

### Check Duplicates Dates

In [23]:
df_date["date"].duplicated().sum()

np.int64(0)

In [24]:
df_date["date"].nunique()

731

### Check Missing Values

In [25]:
df_date.isna().sum()

date              0
year              0
quarter           0
month             0
month_name        0
week              0
day_of_week       0
day               0
is_weekend        0
month_year        0
year_month        0
quarter_number    0
dtype: int64

### Validate Weekend Logic

In [26]:
df_date.groupby(
    "is_weekend"
)["date"].count()

is_weekend
False    419
True     312
Name: date, dtype: int64

In [27]:
df_date[
    df_date["is_weekend"]
].head(10)

,date,year,quarter,month,month_name,week,day_of_week,day,is_weekend,month_year,year_month,quarter_number
4,2024-01-05,2024,Q1,1,January,1,Friday,5,True,2024-01,202401,1
5,2024-01-06,2024,Q1,1,January,1,Saturday,6,True,2024-01,202401,1
6,2024-01-07,2024,Q1,1,January,1,Sunday,7,True,2024-01,202401,1
11,2024-01-12,2024,Q1,1,January,2,Friday,12,True,2024-01,202401,1
12,2024-01-13,2024,Q1,1,January,2,Saturday,13,True,2024-01,202401,1
13,2024-01-14,2024,Q1,1,January,2,Sunday,14,True,2024-01,202401,1
18,2024-01-19,2024,Q1,1,January,3,Friday,19,True,2024-01,202401,1
19,2024-01-20,2024,Q1,1,January,3,Saturday,20,True,2024-01,202401,1
20,2024-01-21,2024,Q1,1,January,3,Sunday,21,True,2024-01,202401,1
25,2024-01-26,2024,Q1,1,January,4,Friday,26,True,2024-01,202401,1

### Validate Months

In [28]:
df_date.groupby(
    ["year", "month"]
)["date"].count()

year  month
2024  1        31
      2        29
      3        31
      4        30
      5        31
      6        30
      7        31
      8        31
      9        30
      10       31
      11       30
      12       31
2025  1        31
      2        28
      3        31
      4        30
      5        31
      6        30
      7        31
      8        31
      9        30
      10       31
      11       30
      12       31
Name: date, dtype: int64

### Save the Date Dimension

In [29]:
Path("../data/raw").mkdir(
    parents=True,
    exist_ok=True
)

In [30]:
df_date.to_csv(
    "../data/raw/dim_date.csv",
    index=False
)

In [31]:
Path(
    "../data/raw/dim_date.csv"
).exists()

True